Repository ethereumclassic/ECIPs, pull requests merged in 2019-10, with the labels that each got.

#156 move ecip 1050 to last call
  _specs/ecip-1050.md
Labels: type: meta

#155 move ecip 1056 to last call
  _specs/ecip-1056.md
Labels: type: meta

#157 ecip-1061: correct the aztlan spelling as per community request
  _specs/ecip-1061.md
Labels: status: draft, type: meta

#145 ECIP-1055: Flyclient - Succinct PoW Using Merkle Mountain Ranges
  _specs/ecip-1055.md
Labels: editor: looks-good, status: draft, type: core

#149 Provided data points, risk considerations, implementation options, references.
  _specs/ecip-1043.md
Labels: status: draft, type: core

#154 invoke-signer draft 0
  _specs/invoke-signer.md
Labels: status: draft, type: meta
