Repository ethereumclassic/ECIPs, pull requests merged in 2019-11, with the labels that each got.

#166 Moving to Withdrawn Status
  _specs/ecip-1016.md
Labels: editor: enhancement, type: meta

#168 Adjusted format of template ECIP to fit ECIP-1000
  ecip-X.md
Labels: editor: enhancement

#167 Adding author and license to ECIP-1015
  _specs/ecip-1015.md
Labels: type: core

#171 ECIP-1070: ProgPoW for ETC
  _specs/ecip-1070.md
Labels: GFY, status: draft, type: core

#170 ECIP-1040, ECIP-1068 and ECIP-1069: Account Versioning ECIPs and Extensions
  _specs/ecip-1040.md
  _specs/ecip-1068.md
  _specs/ecip-1069.md
Labels: status: draft, type: core

#179 ECIP-1071: Methods to Merge Ethereum Blockchains Together
  _specs/ecip-1071.md
Labels: status: draft, type: core

#184 ECIP-1072, ECIP-1073, ECIP-1074: Backward Compatible Options for Istanbul Hard Forks
  _specs/ecip-1072.md
  _specs/ecip-1073.md
  _specs/ecip-1074.md
Labels: status: draft

#181 Create SECURITY.md
  SECURITY.md
Labels: dependencies, editor: enhancement

#199 ecip-1061: move aztlan to last call
  _specs/ecip-1061.md
Labels: editor: looks-good, status: last-call, type: meta

#198 ECIP-1072: Fix name and move it to last call
  _specs/ecip-1072.md
Labels: status: last-call
