Repository ethereumclassic/ECIPs, pull requests merged in 2019-06, with the labels that each got.

#85 ECIP-1054: Atlantis was accepted with target 8_772_000
  ECIPs/ECIP-1054.md
Labels: Accepted

#88 Adjustment of the ECIP process text and docs
  README.md
Labels: Meta

#99 Changed ECIP-1000 link
  README.md
  ecip-X.md
Labels: editor: looks-good

#2 Fix organization
  _specs/ecip-1039.md
  _specs/ecip-1041.md
Labels: editor: looks-good, editor: on-hold
