Repository ethereumclassic/ECIPs, pull requests merged in 2020-09, with the labels that each got.

#340 ECIP-1094: Integration of VeriBlock Proof-of-Proof into Ethereum Classic
  _specs/ecip-1094.md
  assets/ecip-1094/etc_header_hash_format.png
  assets/ecip-1094/etc_vbk_flow.png
  assets/ecip-1094/si_inheriting_attack.png
  assets/ecip-1094/si_inheriting_attack_resolved.png
  assets/ecip-1094/si_inheriting_no_competition.png
Labels: editor: 3 grumble, status: 0 wip, type: core

#349 ECIP-1098 proto-Treasury system for ETC
  _specs/ecip-1098.md
Labels: editor: 1 needs review, status: 0 wip, type: core

#347 ECIP-1097 Checkpointing for 51% Attack Resistance
  _specs/ecip-1097.md
Labels: editor: 1 needs review, status: 0 wip, type: core

#344 ECIP 1096: 51% Attack protection system based on Bitcoin Merged Mining
  _specs/ecip-1096.md
Labels: editor: 7 looks-good, status: 0 wip, type: core

#367 ECIP 1099: Calibrate Epoch Duration
  _specs/ecip-1099.md
Labels: editor: 7 looks-good, status: 1 draft, type: core

#356 Update ECIP-1043 DAG Size Restriction with Recommended Implementation
  _specs/ecip-1043.md
Labels: editor: 7 looks-good, status: 5 last-call, type: core

#369 ECIP-1043: fix review year
  _specs/ecip-1043.md
Labels: editor: 7 looks-good, status: 5 last-call, type: core

#370 ECIP 1043: Move to Replaced by 1099
  _specs/ecip-1043.md
Labels: editor:5 needs-review, status:2 replaced, type: std-core

#372 ECIP 1095: reject in favor of Keccak (1049)
  _specs/ecip-1095.md
Labels: editor:7 looks-good, status:8 rejected, type: std-core

#373 ECBP-1100: Modified Exponential Subjective Scoring
  _specs/ecip-1100.md
Labels: editor:7 looks-good, status:1 draft, type: std-ecbp

#376 Change Status of ecip-1093.md to Withdrawn
  _specs/ecip-1093.md
Labels: editor:9 perfect, status:7 withdrawn, type: std-core

#381 resolving build errors
  _specs/ecip-1043.md
Labels: editor:9 perfect, meta:7 website

#378 doc: Remove Yaz as ECIP Editor
  _specs/ecip-1000.md
Labels: editor:7 looks-good, meta:3 process, status:4 active, type: meta

#384 ECIP/ECBP-1100 MESS: adopt polynomial function, update code
  _specs/ecip-1100.md
Labels: editor:7 looks-good, status:1 draft, type: std-ecbp

#371 ECIP 1099: Add block numbers and move to Last Call
  _specs/ecip-1099.md
Labels: editor:5 needs-review, meta:1 governance, status:5 last-call, type: std-core

#385 ECIP/ECBP-1100: MESS: status update, block numbers
  _specs/ecip-1100.md
Labels: editor:7 looks-good, status:4 active, type: std-ecbp
