Repository ethereumclassic/ECIPs, pull requests merged in 2020-02, with the labels that each got.

#203 ECIP-1063: Reject "Integrated decentralized oracles and smart contracts"
  _specs/ecip-1063.md
Labels: editor: grumble

#259 ECIP-1084: Hard cap on the gaslimit for the ETC mainnet as an in-protocol consensus rule.
  _specs/ecip-1084.md
Labels: editor: enhancement

#293 ECIP-1086: SLOAD Gas Patch for the Testnets
  _specs/ecip-1086.md
Labels: status: draft, type: core

#291 ECIP-1082: Last Call
  _specs/ecip-1082.md
Labels: status: last-call
