Repository ethereumclassic/ECIPs, pull requests merged in 2020-08, with the labels that each got.

#328 ECIP-1092 51% attack solution: PirlGuard & Callisto implementation
  _specs/ecip-51attack-solution.md
Labels: WIP, type: core

#330 ECIP-1093: Change the ETC Proof of Work Algorithm to RandomX
  _specs/ecip-randomX.md
Labels: WIP, type: core

#338 Bump jeykill and kramdown
  Gemfile
  Gemfile.lock
Labels: bot: dependencies, editor: 7 looks-good

#334 Move ECIP-1088 "Phoenix" to Final.
  _specs/ecip-1088.md
Labels: editor: 7 looks-good, status: 9 final, type: meta

#335 Withdraw ECIP-1080 "SELFBALANCE"
  _specs/ecip-1080.md
Labels: editor: 7 looks-good, status: 7 withdrawn, type: core

#336 Fix number and path of ECIP 1093 "RandomX"
  _specs/ecip-1093.md
Labels: editor: 7 looks-good, status: 1 draft, type: core

#337 Fix path of ECIP 1092 "PirlGuard"
  _specs/ecip-1092.md
Labels: editor: 7 looks-good, status: 1 draft, type: core

#346 Update ecip-1092.md
  _specs/ecip-1092.md
Labels: editor: 7 looks-good, status: 1 draft, type: core

#351 Fixed author and name to exclude symbols preventing ECIP from rendering
  _specs/ecip-1092.md
Labels: editor: 7 looks-good, status: 1 draft, type: core

#341 ECIP-1095:feat: add vanilla sha-3 ecip draft
  _specs/ecip-1095.md
Labels: editor: 3 grumble, status: 0 wip, type: core

#353 Move ECIP-1043 DAG-Size Limit to Last Call
  _specs/ecip-1043.md
Labels: editor: 1 needs review, status: 5 last-call, type: core

#354 Move ECIP-1049 "Keccak256" to Last Call
  _specs/ecip-1049.md
Labels: editor: 1 needs review, status: 5 last-call, type: core

#355 Move ECIP-1095 "SHA-3" to Last Call
  _specs/ecip-1095.md
Labels: editor: 1 needs review, status: 5 last-call, type: core
