Repository ethereumclassic/ECIPs, pull requests merged in 2021-02, with the labels that each got.

#404 Update ecip-1000.md
  _specs/ecip-1000.md
Labels: editor:5 needs-review, meta:1 governance, status:4 active

#396 1099: fix epoch number and add resources
  _specs/ecip-1099.md
Labels: editor:5 needs-review, status:3 accepted, type: std-core

#398 1099: move to final
  _specs/ecip-1099.md
Labels: editor:5 needs-review, status:9 final, type: std-core

#402 1000: add faraggi as editor
  _specs/ecip-1000.md
Labels: editor:5 needs-review, meta:1 governance, meta:3 process, status:4 active, type: meta

#400 Admin Clean Up on ecip-1049.md
  _specs/ecip-1049.md
Labels: editor:5 needs-review, status:5 last-call, type: std-core

#409 ECIP-1000: Updating process.png file
  assets/ecip-1000/process.png
Labels: editor:1 grumble, meta:3 process, status:4 active, type: meta

#413 Issues #393 and #358 solved
  _includes/eipnums.html
  networking.html
Labels: editor:7 looks-good, meta:7 website

#411 ECIP 1103: Magneto EVM and Protocol Upgrades
  _specs/ecip-1103.md
Labels: editor:7 looks-good, status:1 draft, type: std-core
