Repository ethereumclassic/ECIPs, pull requests merged in 2022-03, with the labels that each got.

#445 Add ECIP-1107 - Proof of Work Transition Process Testing
  _specs/ecip-1107.md
Labels: status:0 wip, type: informational, meta:7 website

#482 Fix Formatting Errors
  _specs/ecip-1082.md
  _specs/ecip-1083.md
  _specs/ecip-1085.md
  _specs/ecip-1095.md
  _specs/ecip-1096.md
Labels: meta:7 website

#483 Update 1049 Title to appropriate status per ECIP-1000
  _specs/ecip-1049.md
Labels: status:0 wip

#484 1107 - Add status Disclaimer
  _specs/ecip-1107.md
Labels: status:0 wip
