Repository ethereumclassic/ECIPs, pull requests merged in 2022-02, with the labels that each got.

#473 Update ecip-1066.md
  _specs/ecip-1066.md
Labels: type: meta

#474 Fix Author format, Fix File path
  _specs/ecip-1091.md
Labels: meta:7 website

#475 Fix Author format for website
  _specs/ecip-1087.md
Labels: meta:7 website

#476 Fix 0001 ref on 1081 to 1090
  _specs/ecip-1081.md
  _specs/ecip-1090.md
Labels: meta:7 website

#481 Add devcontainer config
  .devcontainer/Dockerfile
  .devcontainer/base.Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/post-create.sh
  .gitignore
  .vscode/tasks.json
Labels: editor:6 enhancement, meta:7 website

#480 Add github handles for authors
  _specs/ecip-1000.md
Labels: meta:7 website, meta:3 process
